// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzsonumsxavkscaowxto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6c29udW1zeGF2a3NjYW93eHRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NjI4NjEsImV4cCI6MjA2MTAzODg2MX0.sVk214daSHqAvXbOGIYADaLrM29D-TFoKB8gO8-vii4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);